assistant = {
   'transcriber': {},
   'model': {},
   'voice': {},
   'firstMessage': "",
   'firstMessageInterruptionsEnabled': False,
   'firstMessageMode': 'assistant-speaks-first',
   'voicemailDetection': {},
   'clientMessages': (),
   'serverMessages': (),
   'maxDurationSeconds': 300,
   'backgroundSound': 'office',
   'modelOutputInMessagesEnabled': False,
   'transportConfigurations': [],
   'observabilityPlan': {},
   'credentials': [],
   'hooks': [],
   'name': "",
   'voicemailMessage': "",
   'endCallMessage': "",
   'endCallPhrases': [],
   'compliancePlan': {},
   'metadata': {},
   'backgroundSpeechDenoisingPlan': {},
   'analysisPlan': { 'minMessagesThreshold': 2, 'summaryPlan': {}, 'structuredDataPlan': {},
                  'structuredDataMultiPlan': [], 'successEvaluationPlan': {} },
   'artifactPlan': { 'recordingEnabled': False, 'recordingFormat': 'mp3', 'videoRecordingEnabled': False,
                  'pcapEnabled': False, 'pcapS3PathPrefix': '/'},
   'messagePlan': { 'idleMessages': [], 'idleMessageMaxSpokenCount': 3, 'idleMessageResetCountOnUserSpeechEnabled': False, 
                  'idleTimeoutSeconds': 10, 'silenceTimeoutMessage': ""},
   'startSpeakingPlan': { 'waitSeconds': 3, 'smartEndpointingPlan': {}, 'customEndpointingRules': [], 
                        'transcriptionEndpointingPlan': {} },
   'stopSpeakingPlan': { 'numWords': 0, 'voiceSeconds': 0.3, 'backoffSeconds': 5, 
                        'acknowledgementPhrases': [], 'interruptionPhrases': [] },
   'monitorPlan': { 'listenEnabled': False, 'listenAuthenticationEnabled': False, 
                  'controlEnabled': False, 'controlAuthenticationEnabled': False },
   'credentialIds': [],
   'server': {},
   'keypadInputPlan': { 'enabled': False },
   'backgroundDenoisingEnabled': False
}
